import { Button } from "@nextui-org/react";
import { Book } from "lucide-react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {

  return (
    <>
      <Head>
        <title>Issue tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-[calc(100vh-5rem)] flex-col items-center justify-center bg-gradient-to-b">
        <section id="hero" className="flex flex-col items-center px-6 pt-16 text-center md:pt-14 lg:pt-14 gap-4">
          <h1 className="mt-6 text-5xl font-bold tracking-tight lg:text-6xl max-w-[75ch] duration-500 animate-in fade-in-5 slide-in-from-bottom-2">
            Track your projects with ease
          </h1>
          <p className="text-pretty max-w-[75ch] text-sm duration-700 animate-in fade-in-5 slide-in-from-top-2 md:text-base [&amp;:not(:first-child)]:mt-6">
            Issue Tracker is a simple and easy-to-use project management tool that helps you keep track of your projects and tasks.
          </p>
          <div className="mt-8 items-center justify-center gap-x-3 space-y-3 duration-700 animate-in fade-in-30 sm:flex sm:space-y-0">
            <Button href="/me/projects" as={Link} size="lg" variant="flat" color="default">
              <Book size={15} />
              <span>Create a project</span>
            </Button>
            {/* <a className="inline-flex items-center space-x-3 justify-center whitespace-nowrap text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50 dark:focus-visible:ring-neutral-700 focus-visible:ring-neutral-500 bg-neutral-800 text-neutral-50 shadow hover:bg-neutral-800/90 dark:bg-neutral-800 dark:text-neutral-100 dark:hover:bg-neutral-700/50 h-12 rounded-md px-5 group" href="/dashboard"> */}
            {/* </a> */}
          </div>
        </section>
      </main>
    </>
  );
}
